#ifndef __HARDWARE_H__
#define __HARDWARE_H__

//步进电机引脚
#define SREPPER_MOTOR1_DIR_PORT
#define SREPPER_MOTOR1_STEP_PORT
#define SREPPER_MOTOR2_DIR_PORT
#define SREPPER_MOTOR2_STEP_PORT

#define SREPPER_MOTOR1_DIR_PIN
#define SREPPER_MOTOR1_STEP_PIN
#define SREPPER_MOTOR2_DIR_PIN
#define SREPPER_MOTOR2_STEP_PIN

//驱动电机1方向引脚
//驱动电机1PWM引脚
//驱动电机2方向引脚
//驱动电机2PWM引脚

#endif